# Generated by Django 6.0.2 on 2026-03-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, choices=[('hinjewadi', 'Hinjewadi'), ('wakad', 'Wakad'), ('nigdi', 'Nigdi'), ('akurdi', 'Akurdi'), ('pimple_saudagar', 'Pimple Saudagar'), ('pimple_nilakh', 'Pimple Nilakh'), ('bhumkar_chowk', 'Bhumkar Chowk'), ('tathawade', 'Tathawade'), ('kharadi', 'Kharadi'), ('viman_nagar', 'Viman Nagar'), ('khadki', 'Khadki'), ('chinchwad', 'Chinchwad'), ('pimpri', 'Pimpri'), ('bhosari', 'Bhosari'), ('dapodi', 'Dapodi'), ('kasba_pune', 'Kasba (Pune)'), ('shivaji_nagar', 'Shivaji Nagar'), ('deccan', 'Deccan'), ('koregaon_park', 'Koregaon Park'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='carpet_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Pimpri Chinchwad', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('commercial', 'Commercial'), ('flat', 'Flat'), ('penthouse', 'Penthouse'), ('row_house', 'Row House'), ('plot', 'Plot/Land')], max_length=20),
        ),
    ]
